#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p \
  /config/{log/fail2ban,fail2ban/filter.d}

# copy/update the fail2ban config defaults to/in /config
cp -nR /defaults/fail2ban /config

cp -nR /etc/fail2ban/filter.d/common.conf /config/fail2ban/filter.d/common.conf


# permissions
chown -R abc:abc \
  /config
